# Generated by Django 4.0.3 on 2023-09-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_automobilevo_manufacturer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
        migrations.AddField(
            model_name='sale',
            name='sold_price',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='suggested_value',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=12),
            preserve_default=False,
        ),
    ]
