# Generated by Django 4.0.3 on 2023-09-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_remove_sale_price_sale_sold_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='suggested_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
