# Generated by Django 4.0.3 on 2023-09-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_sale_suggested_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='suggested_value',
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='suggested_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
