# Generated by Django 4.0.3 on 2023-09-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0003_suggestedpricevo_automobile_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuggestedPriceVO',
            new_name='SuggestedValueVO',
        ),
        migrations.RenameField(
            model_name='automobile',
            old_name='price',
            new_name='suggested_value',
        ),
        migrations.RenameField(
            model_name='suggestedvaluevo',
            old_name='suggested_price',
            new_name='suggested_value',
        ),
    ]
