# Generated by Django 4.0.3 on 2023-09-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0004_rename_suggestedpricevo_suggestedvaluevo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedvaluevo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
